---
to: "src/backend/types/backend.global.d.ts"
---
import {Project, Issue, User} from "@/api/youtrack-types";

// Import extended entities if they exist (generated by vite-plugin-youtrack-extension-properties)
// This allows automatic use of extension properties in context types
type ExtendedIssue = typeof import("@/api/extended-entities") extends { ExtendedIssue: infer T } ? T : Issue;
type ExtendedProject = typeof import("@/api/extended-entities") extends { ExtendedProject: infer T } ? T : Project;
type ExtendedArticle = typeof import("@/api/extended-entities") extends { ExtendedArticle: infer T } ? T : any;
type ExtendedUser = typeof import("@/api/extended-entities") extends { ExtendedUser: infer T } ? T : User;
type AppGlobalStorageExtensionProperties = typeof import("@/api/extended-entities") extends { AppGlobalStorageExtensionProperties: infer T } ? T : Record<string, unknown>;

type HttpResponse = {
  body: string | null;
  bodyAsStream: unknown | null;
  code: number;
  json: (object: unknown) => void;
  text: (string: string) => HttpResponse;
  addHeader: (header: string, value: string | null) => HttpResponse;
  /** @deprecated Use code instead */
  status?: number;
};

declare global {
  type AppSettings = Record<string, unknown> & {
    // Add your app-specific settings here
    // Example:
    // someProject?: string | unknown;
    // someFieldName?: string;
    // customLinkType?: string;
  };

  /**
   * Context type for POST requests
   * @template TBody - Request body type
   * @template R - Response type
   * @template Q - Query parameters type (optional, defaults to Record<string, unknown>)
   */
  type CtxPost<
    TBody = Record<string, unknown>,
    R = Record<string, unknown>,
    Q = Record<string, unknown>
  > = {
    /** Available when scope is 'issue' - automatically uses ExtendedIssue if extension properties are defined */
    issue?: ExtendedIssue;
    /** Available when scope is 'project' - automatically uses ExtendedProject if extension properties are defined */
    project?: ExtendedProject;
    /** Available when scope is 'article' - automatically uses ExtendedArticle if extension properties are defined */
    article?: ExtendedArticle;
    /** Available when scope is 'user' - automatically uses ExtendedUser if extension properties are defined */
    user?: ExtendedUser;
    /** Current user making the request */
    currentUser: User;
    /** App settings */
    settings: AppSettings;
    /** Global storage extension properties - automatically uses AppGlobalStorageExtensionProperties if defined */
    globalStorage?: {
      extensionProperties?: AppGlobalStorageExtensionProperties;
    };
    request: {
      body: string;
      bodyAsStream: unknown;
      headers: Array<{ name: string; value: string }>;
      path: string;
      fullPath: string;
      method: 'GET' | 'POST' | 'PUT' | 'DELETE';
      parameterNames: Array<string>;
      json: () => TBody;
      getParameter: (name: string) => string | undefined;
      getParameters: (name: string) => Array<string>;
      query: Q;
    };
    response: HttpResponse;
  };

  /**
   * Context type for PUT requests
   * @template TBody - Request body type
   * @template R - Response type
   * @template Q - Query parameters type (optional, defaults to Record<string, unknown>)
   */
  type CtxPut<
    TBody = Record<string, unknown>,
    R = Record<string, unknown>,
    Q = Record<string, unknown>
  > = {
    /** Available when scope is 'issue' - automatically uses ExtendedIssue if extension properties are defined */
    issue?: ExtendedIssue;
    /** Available when scope is 'project' - automatically uses ExtendedProject if extension properties are defined */
    project?: ExtendedProject;
    /** Available when scope is 'article' - automatically uses ExtendedArticle if extension properties are defined */
    article?: ExtendedArticle;
    /** Available when scope is 'user' - automatically uses ExtendedUser if extension properties are defined */
    user?: ExtendedUser;
    /** Current user making the request */
    currentUser: User;
    /** App settings */
    settings: AppSettings;
    /** Global storage extension properties - automatically uses AppGlobalStorageExtensionProperties if defined */
    globalStorage?: {
      extensionProperties?: AppGlobalStorageExtensionProperties;
    };
    request: {
      body: string;
      bodyAsStream: unknown;
      headers: Array<{ name: string; value: string }>;
      path: string;
      fullPath: string;
      method: 'GET' | 'POST' | 'PUT' | 'DELETE';
      parameterNames: Array<string>;
      json: () => TBody;
      getParameter: (name: string) => string | undefined;
      getParameters: (name: string) => Array<string>;
      query: Q;
    };
    response: HttpResponse;
  };

  /**
   * Context type for GET requests
   * @template R - Response type
   * @template Q - Query parameters type (optional, defaults to Record<string, unknown>)
   */
  type CtxGet<
    R = Record<string, unknown>,
    Q = Record<string, unknown>
  > = {
    /** Available when scope is 'issue' - automatically uses ExtendedIssue if extension properties are defined */
    issue?: ExtendedIssue;
    /** Available when scope is 'project' - automatically uses ExtendedProject if extension properties are defined */
    project?: ExtendedProject;
    /** Available when scope is 'article' - automatically uses ExtendedArticle if extension properties are defined */
    article?: ExtendedArticle;
    /** Available when scope is 'user' - automatically uses ExtendedUser if extension properties are defined */
    user?: ExtendedUser;
    /** Current user making the request */
    currentUser: User;
    /** App settings */
    settings: AppSettings;
    /** Global storage extension properties - automatically uses AppGlobalStorageExtensionProperties if defined */
    globalStorage?: {
      extensionProperties?: AppGlobalStorageExtensionProperties;
    };
    request: {
      body: string;
      bodyAsStream: unknown;
      headers: Array<{ name: string; value: string }>;
      path: string;
      fullPath: string;
      method: 'GET' | 'POST' | 'PUT' | 'DELETE';
      parameterNames: Array<string>;
      json: () => never;
      getParameter: (name: string) => string | undefined;
      getParameters: (name: string) => Array<string>;
      query: Q;
    };
    response: HttpResponse;
  };

  /**
   * Context type for DELETE requests
   * @template R - Response type
   * @template Q - Query parameters type (optional, defaults to Record<string, unknown>)
   */
  type CtxDelete<
    R = Record<string, unknown>,
    Q = Record<string, unknown>
  > = {
    /** Available when scope is 'issue' - automatically uses ExtendedIssue if extension properties are defined */
    issue?: ExtendedIssue;
    /** Available when scope is 'project' - automatically uses ExtendedProject if extension properties are defined */
    project?: ExtendedProject;
    /** Available when scope is 'article' - automatically uses ExtendedArticle if extension properties are defined */
    article?: ExtendedArticle;
    /** Available when scope is 'user' - automatically uses ExtendedUser if extension properties are defined */
    user?: ExtendedUser;
    /** Current user making the request */
    currentUser: User;
    /** App settings */
    settings: AppSettings;
    /** Global storage extension properties - automatically uses AppGlobalStorageExtensionProperties if defined */
    globalStorage?: {
      extensionProperties?: AppGlobalStorageExtensionProperties;
    };
    request: {
      body: string;
      bodyAsStream: unknown;
      headers: Array<{ name: string; value: string }>;
      path: string;
      fullPath: string;
      method: 'GET' | 'POST' | 'PUT' | 'DELETE';
      parameterNames: Array<string>;
      json: () => never;
      getParameter: (name: string) => string | undefined;
      getParameters: (name: string) => Array<string>;
      query: Q;
    };
    response: HttpResponse;
  };
}

//This is needed to make the file a module
export {};

