"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_url": "https://jetbrains.crowdin.com"

preserve_hierarchy: true

files:
  - source: "/translations/default.pot"
    dest: "/widgets/documents-list-widget/default.pot"
    translation: "/translations/translations_%two_letters_code%.po"
